export interface FamilyMember {
    name: string;
    register: string;
    age: string;
    relation: string;
    phone: string;
    employment: string;
}
export interface Education {
    schoolName: string;
    studyMode: string;
    degree: string;
    completionDate: string;
}
export interface Org {
    orgName: string;
    orgType: string;
    orgCompletionDate: string;
}
export interface Learn {
    lName: string;
    lSource: string;
}
export interface Experience {
    comName: string;
    comType: string;
    comOccupation: string;
    comWork: string;
    comExitReason: string;
    comTime: string;
    comConnection: string;
}
export interface Computer {
    computerName: string;
}
export interface Language {
    languageName: string;
    languageSpeak: string;
    languageRead: string;
}
export interface Step2Props {
    formData: jobFormData;
    setFormData: (formData: jobFormData) => void;
    prevStep: () => void;
    submitForm: () => void;
    job: string | string[] | null;
}
export interface jobFormData {
    obog: string;
    ner: string;
    work_type?: string;
    city: string;
    address: string;
    phone1: string;
    phone2: string;
    mail: string;
    born1: string;
    born2: string;
    born3: string;
    married: string;
    register: string;
    gender: string;
    v_education1_1: string;
    v_education1_2: string;
    v_education1_3: string;
    v_education1_4: string;
    v_education2_1: string;
    v_education2_2: string;
    v_education2_3: string;
    v_education2_4: string;
    v_education3_1: string;
    v_education3_2: string;
    v_education3_3: string;
    v_education3_4: string;
    v_education4_1: string;
    v_education4_2: string;
    v_education4_3: string;
    v_education4_4: string;
    v_education5_1: string;
    v_education5_2: string;
    v_education5_3: string;
    v_education5_4: string;
    v_career1_1: string;
    v_career1_2: string;
    v_career1_3: string;
    v_career2_1: string;
    v_career2_2: string;
    v_career2_3: string;
    v_career3_1: string;
    v_career3_2: string;
    v_career3_3: string;
    v_career4_1: string;
    v_career4_2: string;
    v_career4_3: string;
    v_career5_1: string;
    v_career5_2: string;
    v_career5_3: string;
    v_learn1_1: string;
    v_learn1_2: string;
    v_learn2_1: string;
    v_learn2_2: string;
    v_learn3_1: string;
    v_learn3_2: string;
    v_learn4_1: string;
    v_learn4_2: string;
    v_learn5_1: string;
    v_learn5_2: string;
    ex1_1: string;
    ex1_2: string;
    ex1_3: string;
    ex1_4: string;
    ex1_5: string;
    ex1_6: string;
    ex1_7: string;
    ex2_1: string;
    ex2_2: string;
    ex2_3: string;
    ex2_4: string;
    ex2_5: string;
    ex2_6: string;
    ex2_7: string;
    ex3_1: string;
    ex3_2: string;
    ex3_3: string;
    ex3_4: string;
    ex3_5: string;
    ex3_6: string;
    ex3_7: string;
    car_learn: string;
    salary: string;
    sale_learn: string;
    computer1_1: string;
    computer2_1: string;
    computer3_1: string;
    computer4_1: string;
    computer5_1: string;
    lg1_1: string;
    lg1_2: string;
    lg1_3: string;
    lg2_1: string;
    lg2_2: string;
    lg2_3: string;
    lg3_1: string;
    lg3_2: string;
    lg3_3: string;
    lg4_1: string;
    lg4_2: string;
    lg4_3: string;
    lg5_1: string;
    lg5_2: string;
    lg5_3: string;
    other_talent: string;
    car_password: string;
    car_password_type: string;
    career_skill1: string;
    career_skill2: string;
    hobby: string;
    other_add: string;
    job_contact: string;
    wish_message: string;
    f1_1: string;
    f2_1: string;
    f3_1: string;
    f4_1: string;
    f5_1: string;
    f6_1: string;
    f1_2: string;
    f2_2: string;
    f3_2: string;
    f4_2: string;
    f5_2: string;
    f6_2: string;
    f1_3: string;
    f2_3: string;
    f3_3: string;
    f4_3: string;
    f5_3: string;
    f6_3: string;
    f1_4: string;
    f2_4: string;
    f3_4: string;
    f4_4: string;
    f5_4: string;
    f6_4: string;
    f1_5: string;
    f2_5: string;
    f3_5: string;
    f4_5: string;
    f5_5: string;
    f6_5: string;
    f1_6: string;
    f2_6: string;
    f3_6: string;
    f4_6: string;
    f5_6: string;
    f6_6: string;
    pain: string;
    friend_in_job: string;
    friend_in_job_text: string;
    friend_in_job2: string;
    send_word: string;
    biznes_travel: string;
    last_check: string;
    reason: string;
    file: any
}

export const defaultJobFormData: jobFormData = {
    obog: '',
    ner: '',
    work_type: '',
    city: '',
    address: '',
    phone1: '',
    phone2: '',
    mail: '',
    born1: '',
    born2: '',
    born3: '',
    married: '',
    register: '',
    gender: '',
    v_education1_1: '',
    v_education1_2: '',
    v_education1_3: '',
    v_education1_4: '',
    v_education2_1: '',
    v_education2_2: '',
    v_education2_3: '',
    v_education2_4: '',
    v_education3_1: '',
    v_education3_2: '',
    v_education3_3: '',
    v_education3_4: '',
    v_education4_1: '',
    v_education4_2: '',
    v_education4_3: '',
    v_education4_4: '',
    v_education5_1: '',
    v_education5_2: '',
    v_education5_3: '',
    v_education5_4: '',
    v_career1_1: '',
    v_career1_2: '',
    v_career1_3: '',
    v_career2_1: '',
    v_career2_2: '',
    v_career2_3: '',
    v_career3_1: '',
    v_career3_2: '',
    v_career3_3: '',
    v_career4_1: '',
    v_career4_2: '',
    v_career4_3: '',
    v_career5_1: '',
    v_career5_2: '',
    v_career5_3: '',
    v_learn1_1: '',
    v_learn1_2: '',
    v_learn2_1: '',
    v_learn2_2: '',
    v_learn3_1: '',
    v_learn3_2: '',
    v_learn4_1: '',
    v_learn4_2: '',
    v_learn5_1: '',
    v_learn5_2: '',
    ex1_1: '',
    ex1_2: '',
    ex1_3: '',
    ex1_4: '',
    ex1_5: '',
    ex1_6: '',
    ex1_7: '',
    ex2_1: '',
    ex2_2: '',
    ex2_3: '',
    ex2_4: '',
    ex2_5: '',
    ex2_6: '',
    ex2_7: '',
    ex3_1: '',
    ex3_2: '',
    ex3_3: '',
    ex3_4: '',
    ex3_5: '',
    ex3_6: '',
    ex3_7: '',
    car_learn: '',
    salary: '',
    sale_learn: '',
    computer1_1: '',
    computer2_1: '',
    computer3_1: '',
    computer4_1: '',
    computer5_1: '',
    lg1_1: '',
    lg1_2: '',
    lg1_3: '',
    lg2_1: '',
    lg2_2: '',
    lg2_3: '',
    lg3_1: '',
    lg3_2: '',
    lg3_3: '',
    lg4_1: '',
    lg4_2: '',
    lg4_3: '',
    lg5_1: '',
    lg5_2: '',
    lg5_3: '',
    other_talent: '',
    car_password: '',
    car_password_type: '',
    career_skill1: '',
    career_skill2: '',
    hobby: '',
    other_add: '',
    job_contact: '',
    wish_message: '',
    f1_1: '',
    f2_1: '',
    f3_1: '',
    f4_1: '',
    f5_1: '',
    f6_1: '',
    f1_2: '',
    f2_2: '',
    f3_2: '',
    f4_2: '',
    f5_2: '',
    f6_2: '',
    f1_3: '',
    f2_3: '',
    f3_3: '',
    f4_3: '',
    f5_3: '',
    f6_3: '',
    f1_4: '',
    f2_4: '',
    f3_4: '',
    f4_4: '',
    f5_4: '',
    f6_4: '',
    f1_5: '',
    f2_5: '',
    f3_5: '',
    f4_5: '',
    f5_5: '',
    f6_5: '',
    f1_6: '',
    f2_6: '',
    f3_6: '',
    f4_6: '',
    f5_6: '',
    f6_6: '',
    pain: '',
    friend_in_job: '',
    friend_in_job_text: '',
    friend_in_job2: '',
    send_word: '',
    biznes_travel: '',
    last_check: '',
    reason: '',
    file: null
};
